name: quiz_api_client
description: A Dart API client
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  dio: ^5.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  lints: ^2.0.0